name: Build and Deploy to GKE

on:
  push:
    branch:
      -main
      
env:
  PROJECT_ID: ${{secrets.GKE_PROJECT}}
  GKE_CLUSTER: github-action-gke
  GKE_ZONE: us-central1
  DEPLOYMENT_NAME: github-action-gke
  IMAGE: github-action-gke-image
  TAG: 1.0.0
  
jobs:
  setup-build-publish-deploy:
    name: Setup Build Publish Deploy
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: github
          settings-path: ${{github.workspace}}
          
      - name: Build with maven
        run:  mvn clean package -DskipTests
        
      - name: Setup Google Cloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          service_account_key: ${{secrets.GKE_SA_KEY}}
          project_id: ${{secrets.GKE_PROJECT}}
          
      - name: Configure Docker
        run: |-
          gcloud --quiet auth configure-docker
          
      - name: Set GKE Credetials
        run: |-
          gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
          
      - name: Build Docker Image
        run: |-
          docker build --tag "gcr.io/$PROJECT_ID/$IMAGE:$TAG" .
          
      - name: Publish Docker Image
        run: |-
          docker push "gcr.io/$PROJECT_ID/$IMAGE:$TAG"
          
      - name: Setup Kustomize
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize
          
      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: ${{$PROJECT_ID}}
          region: us-central1
          # NOTE: If required, update to the appropriate source folder
          # source: ./
          image: gcr.io/${{PROJECT_ID}}/${{IMAGE}}:${{TAG}}

     
    